from brownian_motion import BrownianMotion
from option import Option
from stock_hedging import StockHedging

import numpy as np

class Simulator:
    """
    Executes a single-path hedging simulation for a single underlying asset.

    This class represents one realization of the price path and corresponding
    hedging actions. It does not perform Monte Carlo aggregation or statistical
    analysis; instead, it is called by a higher-level Monte Carlo driver to
    generate individual simulation paths.
    """

    def __init__(self, time_unit = "days", transaction_fee_bps = 0, integer_stocks = True):
        """
        Initialise the simulator with global parameters
        :param time_unit: the time unit to simulate (days, months, etc.)
        :param transaction_fee_bps:
        :param integer_stocks: Boolean, if True round all stock amounts to nearest integer
        """
        self.time_unit = time_unit
        self.transaction_fee_bps = transaction_fee_bps
        self.integer_stocks = integer_stocks

    def stock_data(self, init_stock_price, time_to_maturity, mu, sigma, stock_time_step=1/252, seed=12345):
        """
        Generates a stock path to be used in the run_random and run_seed functions.
        :param init_stock_price: Initial Stock Price
        :param time_to_maturity: The simulation time of the stock (Derived from the time of maturity of the option)
        :param mu: Yearly expected drift
        :param sigma: Yearly volatility parameter
        :param stock_time_step: Determines how often the stock price is evaluated. lower step size = more data points
        :param seed: RNG seed
        :return: A list of stock prices corrosponding to the time_to_maturity and stock_time_stem
        """
        # Defining Stock features
        stock = BrownianMotion(x_0=init_stock_price, t=time_to_maturity, delta_t=stock_time_step,
                               mu=mu, sigma=sigma)

        return stock.geometric_brownian_motion(seed)


    def option_data(self, stock_prices, time_expiry_array, option_strike_price, sigma, risk_free_rate):
        """
        Generates option prices, delta and gamma to be used in the run_random, run_seed, run_path.
        :param stock_prices: List of stock prices
        :param time_expiry_array: Contains value of time to expiry for each data point stock_prices
        :param option_strike_price: Strike price of the option
        :param sigma: Model volatility
        :param risk_free_rate: Risk free rate
        :return: tuple of lists (option_price, delta, gamma) evaluated at the timesteps of the stock_prices
        """
        option = Option(K=option_strike_price, sigma=sigma, r=risk_free_rate)

        option_price = option.black_scholes_eu_call(stock_prices, time_expiry_array)
        delta = option.get_delta(stock_prices, time_expiry_array)
        gamma = option.get_gamma(stock_prices, time_expiry_array)

        return option_price, delta, gamma

    def run_random(self,* , time_to_maturity=1, num_options=100, stock_time_step=1/252, num_hedges=12, mu=0.1, sigma_true=0.15,
            sigma_model=0.15, init_stock_price=100, risk_free_rate=0.05, option_strike_price=100, init_cash_balance=0):
        """
        Run a single path hedging simulation of a random stock path
        :param time_to_maturity: Time to maturity of option
        :param num_options: Number of options to be held initially
        :param stock_time_step: Determines how often the stock price is evaluated. lower step size = more data points
        :param num_hedges: Number of times to hedge during the life of the option
        :param mu: Yearly expected drift of the stock
        :param sigma_true: True volatility of the stock
        :param sigma_model: Assumed Volatility of the stock (Used in options pricing)
        :param init_stock_price: Initial stock price
        :param risk_free_rate: Risk free rate
        :param option_strike_price: Strike price of the option
        :param init_cash_balance: Initial cash balance
        :return: Return a tuple two pandas DataFrames generated by assemble_data() function in the StockHedging class
                First DataFrame is evaluated at all the timesteps where stock_prices is evaluated
                Second DataFrame is only evaluated at the timesteps when hedging takes place
                Both DataFrames contains the following columns:
             - "Option Price": Model option price at each timestep
             - "Stock Price": Underlying stock price
             - "Option Delta": Model delta of the option
             - "Options held": Number of option contracts held
             - "Shares held": Total number of shares held after hedging
             - "Hedge in this timestep": Change in hedge position executed at the timestep
             - "Transaction costs": Transaction costs incurred at the timestep
             - "Hedging cashflow this timestep": Cashflow due to hedge adjustment
             - "Total Cashflow": Cumulative cashflow from hedging actions
             - "Cash Balance": Cash account balance
             - "Total Portfolio Value": Combined value of option position, stock position, and cash balance
             - "Total PnL": Cumulative profit and loss of the hedged portfolio
        """

        stock_prices = self.stock_data(init_stock_price, time_to_maturity, mu, sigma_true, stock_time_step, seed=np.random.randint(0, 2**32 - 1))
        n = stock_prices.size
        time_expiry_array = (n - 1 - np.arange(n)) * stock_time_step

        #Defining Options Features
        option_price, delta, gamma = self.option_data(stock_prices, time_expiry_array, option_strike_price, sigma_model, risk_free_rate)

        #Perform Hedging
        stock_hedging = StockHedging(T=time_to_maturity, cash_balance=init_cash_balance,
                                     time_steps=num_hedges,options_amount=num_options, options_price=option_price,
                                     options_delta=delta, stock_prices=stock_prices, r=risk_free_rate,
                                     integer_stocks=self.integer_stocks, transaction_fee_bps=self.transaction_fee_bps)

        return stock_hedging.assemble_data_fulltime(), stock_hedging.assemble_data()

    def run_seed(self,* , time_to_maturity=1, num_options=100, stock_time_step=1/252, num_hedges=12, mu=0.1, sigma_true=0.15,
            sigma_model=0.15, init_stock_price=100, risk_free_rate=0.05, option_strike_price=100, init_cash_balance=0, seed=12345):
        """
        Run a single path hedging simulation of a stock given a specific seed
        :param time_to_maturity: Time to maturity of option
        :param num_options: Number of options to be held initially
        :param stock_time_step: Determines how often the stock price is evaluated. lower step size = more data points
        :param num_hedges: Number of times to hedge during the life of the option
        :param mu: Yearly expected drift of the stock
        :param sigma_true: True volatility of the stock
        :param sigma_model: Assumed Volatility of the stock (Used in options pricing)
        :param init_stock_price: Initial stock price
        :param risk_free_rate: Risk free rate
        :param option_strike_price: Strike price of the option
        :param init_cash_balance: Initial cash balance
        :return: Return a tuple two pandas DataFrames generated by assemble_data() function in the StockHedging class
                First DataFrame is evaluated at all the timesteps where stock_prices is evaluated
                Second DataFrame is only evaluated at the timesteps when hedging takes place
                Both DataFrames contains the following columns:
             - "Option Price": Model option price at each timestep
             - "Stock Price": Underlying stock price
             - "Option Delta": Model delta of the option
             - "Options held": Number of option contracts held
             - "Shares held": Total number of shares held after hedging
             - "Hedge in this timestep": Change in hedge position executed at the timestep
             - "Transaction costs": Transaction costs incurred at the timestep
             - "Hedging cashflow this timestep": Cashflow due to hedge adjustment
             - "Total Cashflow": Cumulative cashflow from hedging actions
             - "Cash Balance": Cash account balance
             - "Total Portfolio Value": Combined value of option position, stock position, and cash balance
             - "Total PnL": Cumulative profit and loss of the hedged portfolio
        """
        stock_prices = self.stock_data(init_stock_price, time_to_maturity, mu, sigma_true, stock_time_step, seed=seed)
        n = stock_prices.size
        time_expiry_array = (n - 1 - np.arange(n)) * stock_time_step

        #Defining Options Features
        option_price, delta, gamma = self.option_data(stock_prices, time_expiry_array, option_strike_price, sigma_model, risk_free_rate)

        #Perform Hedging
        stock_hedging = StockHedging(T=time_to_maturity, cash_balance=init_cash_balance,
                                     time_steps=num_hedges,options_amount=num_options, options_price=option_price,
                                     options_delta=delta, stock_prices=stock_prices, r=risk_free_rate,
                                     integer_stocks=self.integer_stocks, transaction_fee_bps=self.transaction_fee_bps)

        return stock_hedging.assemble_data_fulltime(), stock_hedging.assemble_data()

    def run_path(self, stock_prices, stock_time_step, option_strike_price=100, sigma_model=0.15, risk_free_rate=0.05,
                 init_cash_balance=0, num_hedges=12, num_options=100):
        """
        Run a single path hedging simulation, given the price path of the stock
        :param stock_prices: Array of stock prices
        :param stock_time_step: Time step of the stock prices
        :param option_strike_price: Strike price of the option
        :param sigma_model: Assumed Volatility of the stock (Used in options pricing)
        :param risk_free_rate: Risk free rate
        :param init_cash_balance: Initial cash balance
        :param num_hedges: Number of times to hedge during the life of the option
        :param num_options: Number of options to be held initially
        :return: Return a tuple two pandas DataFrames generated by assemble_data() function in the StockHedging class
                First DataFrame is evaluated at all the timesteps where stock_prices is evaluated
                Second DataFrame is only evaluated at the timesteps when hedging takes place
                Both DataFrames contains the following columns:
             - "Option Price": Model option price at each timestep
             - "Stock Price": Underlying stock price
             - "Option Delta": Model delta of the option
             - "Options held": Number of option contracts held
             - "Shares held": Total number of shares held after hedging
             - "Hedge in this timestep": Change in hedge position executed at the timestep
             - "Transaction costs": Transaction costs incurred at the timestep
             - "Hedging cashflow this timestep": Cashflow due to hedge adjustment
             - "Total Cashflow": Cumulative cashflow from hedging actions
             - "Cash Balance": Cash account balance
             - "Total Portfolio Value": Combined value of option position, stock position, and cash balance
             - "Total PnL": Cumulative profit and loss of the hedged portfolio
        """

        stock_prices = stock_prices.copy()

        n = stock_prices.size
        time_expiry_array = (n - 1 - np.arange(n)) * stock_time_step
        time_to_maturity = (n - 1) * stock_time_step

        # Defining Options Features
        option_price, delta, gamma = self.option_data(stock_prices, time_expiry_array, option_strike_price, sigma_model,
                                                      risk_free_rate)
        #Perform hedging
        stock_hedging = StockHedging(T=time_to_maturity, cash_balance=init_cash_balance,
                                     time_steps=num_hedges, options_amount=num_options, options_price=option_price,
                                     options_delta=delta, stock_prices=stock_prices, r=risk_free_rate,
                                     integer_stocks=self.integer_stocks, transaction_fee_bps=self.transaction_fee_bps)

        return stock_hedging.assemble_data_fulltime(), stock_hedging.assemble_data()
